export enum EventStrings {
    DbConnectionLost = "[Core] DbConnectionLost",
    DbReconnected = "[Core] DbReconnected",
    GuildAdd = "[Core] GuildAdd",
    DocumentUpdateError = "[Core] DocumentUpdateError",
    DocumentDeleteError = "[Core] DocumentDeleteError",
    DocumentLoadError = "[Core] DocumentLoadError",
    DetermineCommandError = "[Core] DetermineCommandError",
    SendHeartbeatError = "[Core] SendHeartbeatError",
    InvokeCommandError = "[Core] InvokeCommandError",
    MissingGuildPermissions = "[Core] MissingGuildPermissions",
    MessageSendError = "[Core] MessageSendError",
    MemoryMeasured = "[Core] MemoryMeasured",
    GuildReset = "[Core] GuildReset",
}